<% if File.exist?('rubocop_common.yml') %>
inherit_from:
  - rubocop_common.yml
  - .rubocop_todo.yml
<% else %>
inherit_gem:
  rggen-devtools: config/rubocop_common.yml

inherit_from:
  - .rubocop_todo.yml
<% end %>

Metrics/BlockLength:
  AllowedMethods:
    - base_feature
    - build
    - define_helpers
    - define_list_feature
    - define_list_item_feature
    - define_simple_feature
    - factory
    - setup_plugin
    - vhdl

Naming/VariableNumber:
  AllowedIdentifiers:
    - w1
    - wo1
